services:
    docler_user.bruteforce_defense.counter:
        class: 'Docler\UserBundle\BruteforceDefense\Counter'

    docler_user.authentication.failure.listener:
        class: 'Docler\UserBundle\Event\Listener\AuthenticationFailureListener'
        arguments:
            - '@docler_user.bruteforce_defense.counter'
            - '@request_stack'
        tags: [ { name: kernel.event_listener, event: security.authentication.failure, method: onFail } ]