services:
    docler_user.bruteforce_defense.counter:
        class: 'Docler\UserBundle\BruteforceDefense\BruteforceCounter'
        arguments:
            - '@docler_user.bruteforce_defense.mongo_storage'

    docler_user.bruteforce_defense.mongo_storage:
        class: 'Docler\UserBundle\BruteforceDefense\Storage\MongoStorage'
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '@doctrine_mongodb.odm.default_aggregation_query'

    docler_user.authentication.failure.listener:
        class: 'Docler\UserBundle\Event\Listener\AuthenticationFailureListener'
        arguments:
            - '@docler_user.bruteforce_defense.counter'
            - '@request_stack'
        tags: [ { name: kernel.event_listener, event: security.authentication.failure, method: onFail } ]

    security.authentication.listener.form:
        class: 'Docler\UserBundle\Event\Listener\UsernamePasswordFormAuthenticationListener'
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
            - [ 'setBruteforceCounter', ['@docler_user.bruteforce_defense.counter'] ]
